10 CLS:INPUT "ENTER MATRIX SIZE TO INVERT";N:DIM A(N,2*N),C(N)
20 FOR I = 1 TO N:FOR J = 1 TO N:PRINT@192,CHR$(31);:PRINT@192,"ENTER COLUMN"J" ROW "I;:INPUT A(I,J):NEXT J,I
30 FOR  I = 1 TO N:FOR J = 1 TO N:PRINT A(I,J);:NEXT J:PRINT:NEXT I
40 FOR I = 1 TO N:FOR J = 1 TO N:A(I,J+N)=0:NEXT:FOR I = 1 TO N:A(I,N+I)=1:NEXT:GOSUB 90:IF DV=0PRINT "THERE IS NO ONE DEFINED SOLUTION":END
50 PRINT "DETERMINANT VALUE="DV
60 GOSUB 440
70 FOR I = 1 TO N:FOR J = 1 TO N:PRINT A(I,J+N);:NEXT:PRINT:NEXT
80 END
90 'THIS FINDS THE INVERSE OF A MATRIX USING GAUSSIAN ELIMINATION"
100 FACT=1:M=2
110 FOR I = 1 TO N:IF A(I,I)=0 THEN 150
120 NEXT I:GOTO 170
130 'SWAPS ROWS AND COLUMNS TO PUT NON-ZERO ELEMENTS
140 'ALONG THE DIAGANOL
150 FOR J= 1 TO N:IF J=I THEN NEXT ELSE IF A(I,J)<>0 THEN S=J:D=I:GOSUB 330:GOTO 120ELSE NEXT:FOR J = 1 TO N*2:IFJ=I THEN NEXT ELSE IF A(I,J)<>0 THEN NS=J:D=I:GOSUB 350:GOTO 120 ELSE NEXT
160 'THIS PERFORMS GAUSSIAN ELIMINATION ON THE LOWER TRIANGLE
170 J=1
180 FOR I =NTOMSTEP-1:IFA(I,J)=0THEN 200
190 FOR K = J TO N:IF A(K,J)<>0THEN R=K:MF=-A(I,J)/A(K,J):GOSUB 380ELSENEXTK:DV=0:RETURN
200 NEXT I:M=M+1:J=J+1:IFJ=NTHEN220ELSE 180
210 'THIS PERFORMS GAUSSIAN ELIMINATION ON THE UPPER TRIANGLE
220 M=N-1:J=N
230 FOR I = M TO 1STEP-1:IFA(I,J)=0THEN 240ELSEFORK=JTO1STEP-1:IFA(K,J)<>0THENR=K:MF=-A(I,J)/A(K,J):GOSUB 380ELSE NEXT:DV=0:RETURN
240 NEXTI:M=M-1:J=J-1:IFJ=1THEN290ELSE230
250 'THIS FIRST MULTIPLIES ALONG THE DIAGANOL TO FIND THE
260 'THE VALUE OF THE DETERMINANT OF THE MATRIX, AND THEN DIVIDES
270 'EACH ELEMENT ALONG THE DIAGONAL BY ITSELF TO FIND THE
280 'INVERSE OF THE MATRIX
290 DV=FACT:FOR I = 1 TO N:DV=DV*A(I,I):IF A(I,I)=0 THEN RETURN
300 IF A(I,I)<>1 THEN MF=1/A(I,I):GOSUB 400
310 NEXT:RETURN
320 'THIS SWAPS THE COLUMNS IN S WITH THE COLUMN IN D
330 FOR K = 1 TO N*2:TEMP=A(S,K):A(S,K)=A(D,K):A(D,K)=TEMP:NEXTK:FACT=-FACT:RETURN
340 'THIS SWAPS THE ROW IN S WITH THE ROW IN D
350 FOR K = 1 TO N"TEMP=A(K,S):A(K,S)=A(K,D):A(K,D)=TEMP:NEXTK:FACT=-FACT:RETURN
360 'THIS ADDS TO EACH ELEMENT OR ROW I THE CORRESPONDING
370 'ELEMENT OF ROW R MULTIPLIED BY MF
380 FOR P = 1 TO N*2:A(I,P)=A(I,P)+A(R,P)*MF:NEXT P:RETURN
390 'THIS MULTIPLES EACH ELEMENT OF ROW I BY MF
400 FOR P = 1 TO N*2:A(I,P)=A(I,P)*MF:NEXT P:RETURN
410 'THIS LEFT MULTIPLIES THE INVERSE OF THE MATRIX BY THE
420 'RIGHT HAD SIDE MATRIX TO SOLVE THE EQUATIONS, LEAVING
430 'THE VALUES OF THE COEFFIENTS
440 FOR I = 1 TO N:C(I)=0:FOR K = 1 TO N:C(I)=C(I)+A(I,K+N)*B(K):NEXT K,I:RETURN

